### ISSUE TITLE
Updating/maintainence of the mod

### ISSUE THREAD

**Issue by rikai** [jacksonkimball/AVerySpecialBlueChicken#3]
Hello,

I wasn't sure the best way to reach you, so I figured I'd send a message via nexus and pop an issue on here.

I was wondering if you'd be open to me maintaining/updating the mod on nexus. I enjoy keeping older mods alive, and I've updated AVSBC for personal use. I'd be happy to maintain it separately if desired in case you wished to return at some point.

Let me know if this would be something you'd be okay with! :)

**Comment by jacksonkimball** [comment]
I believe that I responded to you on nexus, and I just saw this. You are more than welcome to update and continue with this mod!
